version: '3.8'

services:
  db:
    container_name: posgres_db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  backend:
    container_name: nest-backend
    env_file: .env
    build:
      context: ./
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db # we put here db because our db is running in another docker container
      - DB_TYPE=${DB_TYPE}
      - DB_PORT=${DB_PORT}
